$(eval $(call addlib,sourcemeta_hydra_test))

SOURCEMETA_HYDRA_TEST_CXXFLAGS-y += --std=c++20

# TODO: Run real unit tests

# HTTP
SOURCEMETA_HYDRA_TEST_SRCS-y += $(SOURCEMETA_HYDRA_TEST_BASE)/main.cc
