name: Hydra

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macos-latest
            cc: clang
            cxx: clang++
            type: static
          - os: macos-latest
            cc: clang
            cxx: clang++
            type: shared
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            type: static
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
            type: static
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            type: shared
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
            type: shared
          - os: windows-latest
            type: static
          - os: windows-latest
            type: shared

          # Sanitizers
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            type: static
            options: -DHYDRA_ADDRESS_SANITIZER:BOOL=ON
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            type: static
            options: -DHYDRA_UNDEFINED_SANITIZER:BOOL=ON

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
      TEST_PORT: 9999
    steps:
      - name: Install dependencies (GNU/Linux)
        if: runner.os == 'linux'
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes clang-format libcurl4-openssl-dev nodejs

      # See https://github.com/actions/runner-images/issues/8659
      - name: Workaround Clang issue (GNU/Linux)
        if: runner.os == 'linux' && matrix.platform.cc == 'clang'
        run: |
          sudo apt-get purge -y g++-13 gcc-13 libstdc++-13-dev
          sudo apt-get install -y --allow-downgrades libstdc++-12-dev libstdc++6=12.* libgcc-s1=12.*

      - uses: actions/checkout@v3
      - name: Install dependencies (macOS)
        if: runner.os == 'macos'
        run: brew bundle
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - run: cmake --version
      - name: Configure Hydra (static)
        if: matrix.platform.type == 'static'
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DHYDRA_TESTS:BOOL=ON
          -DHYDRA_DOCS:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=OFF
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - name: Configure Hydra (shared)
        if: matrix.platform.type == 'shared'
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DHYDRA_TESTS:BOOL=ON
          -DHYDRA_DOCS:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=ON
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - run: cmake --build ./build --config Release --target clang_format_test
      - run: cmake --build ./build --config Release --parallel 4
      - run: >
          cmake --install ./build --prefix ./build/dist --config Release --verbose
          --component sourcemeta_hydra
      - run: >
          cmake --install ./build --prefix ./build/dist --config Release --verbose
          --component sourcemeta_hydra_dev

      # Run stubs
      - name: Run HTTP stub (Windows)
        run: cmd /c "start /b node test\http\stub.js ${{ env.TEST_PORT }}" && Start-Sleep -Seconds 10
        if: runner.os == 'windows'
      - name: Run HTTP stub (*nix)
        run: (node test/http/stub.js ${{ env.TEST_PORT }} &) && sleep 10
        if: runner.os != 'windows'

      # Not every CTest version supports the --test-dir option. If such option
      # is not recognized, `ctest` will successfully exit finding no tests.
      # Better to be sure and `cd` all the time here.
      - run: cd ./build && ctest --build-config Release --output-on-failure --parallel
        env:
          SOURCEMETA_HYDRA_TEST_BASE_URL: localhost:${{ env.TEST_PORT }}
          # See https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
          UBSAN_OPTIONS: print_stacktrace=1

  unikraft:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (GNU/Linux)
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes qemu-system-x86
      - uses: actions/checkout@v3
      - name: Install KraftKit
        run: |
          wget https://github.com/unikraft/kraftkit/releases/download/v0.7.5/kraftkit_0.7.5_linux_amd64.deb
          sudo dpkg -i kraftkit_0.7.5_linux_amd64.deb
          rm kraftkit_0.7.5_linux_amd64.deb

      # TODO: Automate this?
      - run: |
          mkdir -p build/unikraft/rootfs/etc/ssl/certs
          cp -v /etc/ssl/certs/ca-certificates.crt build/unikraft/rootfs/etc/ssl/certs
          cd unikraft && kraft build --target development --jobs 4 --log-type=basic

      - name: Run HTTP stub
        run: (node test/http/stub.js &) && sleep 10
      # TODO: Run using `kraft` once it supports outbound networking configuration
      - run: >
          qemu-system-x86_64
          -machine pc,accel=tcg
          -cpu qemu64,-vmx,-svm,+x2apic,+pdpe1gb
          -nographic
          -vga none
          -rtc base=utc
          -parallel none
          -serial stdio
          -monitor null
          -netdev user,id=hostnet0
          -device virtio-net-pci,netdev=hostnet0,id=net0
          -kernel unikraft/.unikraft/build/development_qemu-x86_64
          -initrd unikraft/.unikraft/build/initramfs-x86_64.cpio
          -m 128
